### ISSUE TITLE
Linux building with MonoDevelop

### ISSUE THREAD

**Issue by catb0t** [uwx/MadSharp#1]
After adding the dependencies including ManagedBass and running the build, I get a "System.DLLNotFoundException" even though `bass.dll` is right there in the folder (twice!)

Mono documentation suggests it's because `bass.so` (the equivalent Linux shared library) is missing, but I don't know how (or if I can) build `bass.so` from ManagedBass. 

do you have any recommendations?

**Comment by uwx** [comment]
I'm not sure if this will work on Linux, the SharpDX sample (that I forked from) I believe uses WinForms and I don't know how well that would work under Mono, but you can try:

1. Make sure you're on the preview version of Mono (stable is unlikely to work)
1. Get libbass.so from http://www.un4seen.com/ and place in project root directory (where the csproj is)
1. Rename it to `bass.so` since that's what [ManagedBass seems to look for](https://github.com/ManagedBass/ManagedBass/blob/master/src/Bass/Shared/Bass/PInvoke/Bass.cs#L27)
1. Add `<None Include="bass.so" CopyToOutputDirectory="Always" />` to the csproj
1. Trigger build and run it

**Comment by catb0t** [comment]
2 hours later, and I haven't yet gotten step 1. the Mono preview to build :D i'll try harder tomorrow, thanks for the tips!

**Comment by uwx** [comment]
You can just install it with your preferred package manager, see https://www.mono-project.com/download/preview/#download-lin

**Comment by catb0t** [comment]
Installing from the repository, `MonoDevelop` is `7.33` and `mono-csc --version` is `5.16`. After doing the rest of those steps, the same `DLLNotFound: "bass"` persists even though `bass.so` is in the `MadSharp/MadSharp` folder.

Removing the `Include="bass.dll"` line from the csproj also doesn't help, I don't know where the problem is

**Comment by uwx** [comment]
Try copying the .so file manually to `bin/Debug/net47` or wherever the .exe (that you run with Mono) went, the csproj rule is meant to do that automatically but it might not be working in your case with MonoDevelop

**Comment by catb0t** [comment]
I tried with `msbuild`, everything seems to be in order 

```
$ msbuild 
Microsoft (R) Build Engine version 15.1.8.0 ( Wed Sep  5 19:27:37 UTC 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/23/2018 2:19:00 PM.
Project "/home/cat/Downloads/MadSharp/MadSharp/MadSharp.csproj" on node 1 (default targets).
GenerateBindingRedirects:
  No suggested binding redirects from ResolveAssemblyReferences.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreGenerateAssemblyInfo:
Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
_CopyFilesMarkedCopyLocal:
  Touching "/home/cat/Downloads/MadSharp/MadSharp/obj/Debug/net47/MadSharp.csproj.CopyComplete".
_CopyOutOfDateSourceItemsToOutputDirectoryAlways:
  Copying file from "/home/cat/Downloads/MadSharp/MadSharp/bass.dll" to "bin/Debug/net47/bass.dll".
  Copying file from "/home/cat/Downloads/MadSharp/MadSharp/bass.so" to "bin/Debug/net47/bass.so".
CopyFilesToOutputDirectory:
  MadSharp -> /home/cat/Downloads/MadSharp/MadSharp/bin/Debug/net47/MadSharp.exe
Done Building Project "/home/cat/Downloads/MadSharp/MadSharp/MadSharp.csproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

the `bin/Debug/net47` directory seems to have all the files 

```
$ ll -h 
total 2.8M
drwxrwxr-x 2 cat cat 4.0K Oct 23 14:13 ./
drwxrwxr-x 3 cat cat 4.0K Oct 20 19:47 ../
-rw-r--r-- 1 cat cat 250K Oct 20 19:46 bass.dll
-rw-r--r-- 1 cat cat 223K Feb  6  2018 bass.so
-rwxrw-r-- 1 cat cat 383K Oct 23 14:13 MadSharp.exe*
-rw-rw-r-- 1 cat cat 208K Oct 23 14:13 MadSharp.pdb
-rwxrw-r-- 1 cat cat  98K Nov  2  2017 ManagedBass.dll*
-rwxrw-r-- 1 cat cat  58K Aug 24 05:58 SharpDX.D3DCompiler.dll*
-rwxrw-r-- 1 cat cat  45K Aug 24 05:59 SharpDX.Desktop.dll*
-rwxrw-r-- 1 cat cat 484K Aug 24 05:59 SharpDX.Direct2D1.dll*
-rwxrw-r-- 1 cat cat 277K Aug 24 05:59 SharpDX.Direct3D11.dll*
-rwxrw-r-- 1 cat cat 148K Aug 24 05:59 SharpDX.DirectInput.dll*
-rwxrw-r-- 1 cat cat 269K Aug 24 05:58 SharpDX.dll*
-rwxrw-r-- 1 cat cat 145K Aug 24 05:59 SharpDX.DXGI.dll*
-rwxrw-r-- 1 cat cat 211K Aug 24 05:59 SharpDX.Mathematics.dll*
```

and yet when running `mono MadSharp.exe` 

```
Unhandled Exception:
System.DllNotFoundException: bass
  at (wrapper managed-to-native) ManagedBass.Bass.Init(int,int,ManagedBass.DeviceInitFlags,intptr,intptr)
  at MadGame.Program.SetupAndRun () [0x00001] in <a742dd4d477b464b8042683423e10b60>:0 
  at MadGame.Program.Main (System.String[] args) [0x00007] in <a742dd4d477b464b8042683423e10b60>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: bass
  at (wrapper managed-to-native) ManagedBass.Bass.Init(int,int,ManagedBass.DeviceInitFlags,intptr,intptr)
  at MadGame.Program.SetupAndRun () [0x00001] in <a742dd4d477b464b8042683423e10b60>:0 
  at MadGame.Program.Main (System.String[] args) [0x00007] in <a742dd4d477b464b8042683423e10b60>:0 
```

Perhaps I need `ManagedBass.so`? or maybe this is a bug in Bass...

**Comment by uwx** [comment]
Mono docs say that it could be an error loading the library, so try doing `MONO_LOG_LEVEL="debug" MONO_LOG_MASK="dll"` before running it to maybe get some information. Also, if you need more immediate help troubleshooting I can add you on Discord, since GitHub doesn't work particularly well for it.

**Comment by uwx** [comment]
Wait I just realized, how are you gonna run a DirectX-based game on Linux?

**Comment by catb0t** [comment]
Thanks for your help, I should have read the docs more closely -- it was looking for `libbass.so` which was the original name, but the `lib` prefix is not on Windows.

And you're right, it didn't even occur to me that SharpDX was DirectX but now I obviously get `error loading library: d3d11.so`

Wine should (might) fix this though, so that's a different issue :D
